config/routes.rb
Rails.application.routes.draw do

  get 'profile', to: "users#show"
  get 'reviwers', to: "users#index"
  get 'reviwer/:id', to: "users#reviwer_show_page", as: "reviwer_show"

  devise_for :users
	root "staticpages#home"

	get "information", to: "staticpages#information"
	get "how_it_works", to: "staticpages#how_it_works"
	get "contact_us", to: "staticpages#contact_us"
	post "contact_us", to: "staticpages#contact_us"
	get "news", to: "news#index"

	resources :news, only: [:create]
	put "news/:id", to: "news#update", as: "update_news"
	delete "news/:id",to: "news#destroy", as: "destoy_news"
	
	post "add_biography", to: "biographies#create"
	put "update_biography", to: "biographies#update"

	post "add_wg", to: "work_genres#create"
	put "update_wg", to: "work_genres#update"
	delete "destroy_wg", to: "work_genres#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/biography.rb
class Biography < ApplicationRecord

	belongs_to :user
end

app/models/manuscript.rb
class Manuscript < ApplicationRecord
	belongs_to :sender
	belongs_to :receiver
end

app/models/news.rb
class News < ApplicationRecord
	belongs_to :user

	has_attached_file :image, styles: { medium: "250x250>", thumb: "150x150>" }, default_url: "cat.jpeg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  default_scope {order("created_at DESC")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable

  has_one :biography, dependent: :destroy
  has_many :workGenres, dependent: :destroy
  has_many :news
  has_many :send_mn, class_name: 'Manuscript', foreign_key: 'sender_id'
  has_many :received_mn, class_name: 'Manuscript', foreign_key: 'receiver_id'
  
  has_attached_file :avatar, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: "cat.jpeg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  enum role: [:user, :reviwer, :admin]

  validates :name, presence: true, length: {maximum: 30}
  validates :role, presence: true	
end

app/models/work_genre.rb
class WorkGenre < ApplicationRecord
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_permitted_parameters_update, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
  end

  def configure_permitted_parameters_update
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :role, :avatar])
  end
end

app/controllers/biographies_controller.rb
class BiographiesController < ApplicationController
 

  def create
  	@biography = Biography.new(biography_params)
  	if @biography.save
  		redirect_to :back, notice: "Биография добавлена"
  	else
  		redirect_to :back, alert: "Биография не добавлена"
  	end
  end

  def update
  	@biography = Biography.find_by(user_id: current_user.id)
  	if @biography.update(biography_params)
  		redirect_to :back, notice: "Биография обновлена"
  	end
  end

  def destroy
  	if Biography.find_by(user_id: params[:id]).destroy
  		redirect_to :back, notice: "Биография удалена"
  	end
  end

  private

  def biography_params
  	params.require(:biography).permit(:slogan, :work_experiance, :bibliography, :user_id)
  end

end

app/controllers/manuscripts_controller.rb
class ManuscriptsController < ApplicationController
  def destroy
  end

  def create
  end

  def index
  end

  def show
  end

  def update
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  
  before_action :authenticate_user!, only: [:create, :update, :destroy]

  def create
  	@news = current_user.news.new(news_params)
  	if @news.save
  		redirect_to :back, notice: "Новость добавлена"
  	end
  end

  def index
  	@news = News.all
  	@newss = News.new
  end

  def update
  	if News.find(params[:id]).update(news_params)
  		redirect_to :back, notice: "Новость обновлена"
  	end
  end

  def destroy
  	if News.find_by(id: params[:id]).destroy
  		redirect_to :back, notice: "Новость удалена"
  	end
  end

  private 

  def news_params
		params.require(:news).permit(:title, :description, :image)
	end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  
	def home
	end

  def information
  end

  def how_it_works
  end

  def news
  end

	def contact_us
  	@name = params[:name]
  	@phone = params[:phone]
  	@email = params[:email]
  	@message = params[:message]
    if @message != nil && @email != nil && @name != nil && @phone != nil
  	  ContactUsMailer.contact_us_mail(@name, @phone, @email, @message).deliver_now 
        flash[:notice] =  "Ваш вопрос отправлен администратору. Ожидайте ответа на ваш email!"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!, only: [:show]

  def index 
  	@users = User.where(role: 0)
  	@reviwers = User.where(role: 1)
  	@admins = User.where(role: 2)
  end

  def show
  	@user = User.find(current_user.id)
    @biography = Biography.new
    @work_genre =  WorkGenre.new
  end

  def reviwer_show_page
    @reviwer = User.find(params[:id])
    @work_genres = @reviwer.workGenres
  end

end

app/controllers/work_genres_controller.rb
  class WorkGenresController < ApplicationController
  before_action :set_user

  def create
  	@work_genre = @user.workGenres.new(work_genre_params)
  	@work_genre.title = params[:title]
  	@work_genre.description = params[:description]
  	@work_genre.price_per_symbol = params[:price_per_symbol]
  	if @work_genre.save
  		redirect_to :back, notice: "Жанр работы добавлен"
  	else
  		redirect_to :back, alert: "Жанр не добавлен"
  	end
  end

  def update
  	if WorkGenre.find(params[:id]).update(work_genre_params)
  		redirect_to :back, notice: "Жанр успешно обновлён"
  	else
  		redirect_to :back, alert: "Жанр не обновлён"
  	end
  end

  def destroy
  	if WorkGenre.find(params[:id]).destroy
  		redirect_to :back, notice: "Жанр удалён"
  	end
  end

  private

  def set_user
  	@user = User.find(params[:user_id])
  end

  def work_genre_params
		params.require(:workgenre).permit(:title, :description, :price_per_symbol)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/biographies_helper.rb
module BiographiesHelper
end

app/helpers/manuscripts_helper.rb
module ManuscriptsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_genres_helper.rb
module WorkGenresHelper
end

app/views/biographies/_create.html.erb
<%= form_for @biography, url: add_biography_path do |f| %>
	<%= f.label "Вступительное слово" %>
	<%= f.text_area :slogan, class: "form-control" %>
	<%= f.label "Опыт работы" %>
	<%= f.text_area :work_experiance, class: "form-control" %>
	<%= f.label "Библиография" %>
	<%= f.text_area :bibliography, class: "form-control" %>
	<%= f.hidden_field :user_id, value: @user.id %>
	<%= f.submit "Добавить биографию" %>
<% end %>

app/views/biographies/_update.html.erb
<h1>Biographies#update</h1>
<p>Find me in app/views/biographies/update.html.erb</p>

app/views/biographies/update.html.erb
<h1>Biographies#update</h1>
<p>Find me in app/views/biographies/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookExpert</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <div class="container-fluid cnt_main">
		  	<div class="col-md-2 sidenav">
		  		<%= render 'layouts/shared/sidebar' %>
		  	</div>
				<div class="col-md-10 col-md-offset-2 bb">
			  	<%= render 'layouts/shared/header' %>
						<% if notice.present? %>
							<p class="notice"><%= notice %></p>
						<% elsif alert.present? %>
				     	<p class="alert"><%= alert %></p>
			     	<% end %>
		    	<%= yield %>
				</div>
		</div>
  </body>
  
	<footer class="navbar-fixed-bottom">
  	<%= render 'layouts/shared/footer' %>
  </footer>
  
</html>

app/views/layouts/shared/_footer.html.erb
<h5 class="text-center">Экспертиза <span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span> 2016
<em class="pull-right">info@critic.studio Москва</em></h5>

app/views/layouts/shared/_header.html.erb
  <nav class="navbar">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
		      <li><a class="glyphicon glyphicon-briefcase" href="/profile"> <%= current_user.name %></a></li>
		      <li><a class="glyphicon glyphicon-log-out" href="/users/sign_out" data-method="delete"> Выйти</a></li>
		      <% if current_user.role == 2 %>
		      	<li><a class="glyphicon glyphicon-log-out" href="#">Статистика</a></li>
		      	<li><a class="glyphicon glyphicon-log-out" href="#">Новый рецензент</a></li>
		      <% end %>
        <% else %>
        	<li><a class="glyphicon glyphicon-log-in" href="/users/sign_in"> Вход</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/shared/_sidebar.html.erb
<a class="navbar-brand glyphicon glyphicon-book" href="/">Книжная Экспертиза</a>
<hr><br><br><br><br>

<ul class="nav nav-pills nav-stacked">
  <li><a class="glyphicon glyphicon-home" href="/"> Главная</a></li>
  <li><a class="glyphicon glyphicon-pencil" href="/reviwers"> Рецензенты</a></li>
  <li><a class="glyphicon glyphicon-cog" href="/how_it_works"> Как это работает?</a></li>
  <li><a class="glyphicon glyphicon-info-sign" href="/information"> Информация</a></li>
  <li><a class="glyphicon glyphicon-bullhorn" href="/news"> Новости и конкурсы</a></li>
  <li><a class="glyphicon glyphicon-send" href="/contact_us"> Контакты</a></li>
</ul><br>

app/views/manuscripts/create.html.erb
<h1>Manuscripts#create</h1>
<p>Find me in app/views/manuscripts/create.html.erb</p>

app/views/manuscripts/destroy.html.erb
<h1>Manuscripts#destroy</h1>
<p>Find me in app/views/manuscripts/destroy.html.erb</p>

app/views/manuscripts/index.html.erb
<h1>Manuscripts#index</h1>
<p>Find me in app/views/manuscripts/index.html.erb</p>

app/views/manuscripts/show.html.erb
<h1>Manuscripts#show</h1>
<p>Find me in app/views/manuscripts/show.html.erb</p>

app/views/manuscripts/update.html.erb
<h1>Manuscripts#update</h1>
<p>Find me in app/views/manuscripts/update.html.erb</p>

app/views/news/index.html.erb
<%if user_signed_in? && current_user.role == "admin" %>
	<button type="button" class="btn btn-info btn-md btn-block" data-toggle="modal" data-target="#createModal">Добавить новость</button>
<% end %>

<% @news.each do |n| %>

	<div class="media">
	  <a class="media-left" href="#">
	  	<%= image_tag n.image.url(:thumb) %>
	  </a>
	  <div class="media-body">
	    <h4 class="media-heading"><%= n.title %></h4>
	    <%= n.description %>
		    <%if user_signed_in? && current_user.role == "admin" %>
			    <hr>
	    		<%= link_to "Удалить", destoy_news_path(n), method: :delete, class: "btn btn-danger" %>
					<button type="button" class="btn btn-warning btn-md" data-toggle="modal" data-target="#updateModal">Изменить новость</button>
    		<% end %>
	  </div>
	</div>

	<!-- Modal Update -->
	<div id="updateModal" class="modal fade" role="dialog">
	  <div class="modal-dialog modal-lg">

	    <!-- Modal content-->
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal">&times;</button>
	        <h4 class="modal-title">Форма изменения новости</h4>
	      </div>
	      <div class="modal-body">
	        <%= form_for n, url: update_news_path(n.id), method: :put do |f| %>
	        	<%= f.label "Заголовок новости" %><br>
	        	<%= f.text_field :title, class: "form-control", autofocus: true, required: true  %>
	        	<%= f.label "Новое фото" %>
	        	<%= f.file_field :image %>
	        	<%= f.label "Текст новости" %>
	        	<%= f.text_area :description, class: "form-control", autofocus: true, required: true  %>
	        	<%= f.submit "Обновить новость" %>
	        <% end %>
	      </div>
	    </div>

	  </div>
	</div>
<% end %>

<!-- Modal Create -->
<div id="createModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Форма создания новости</h4>
      </div>
      <div class="modal-body">
        <%= form_for @newss, url: news_index_path do |f| %>
        	<%= f.label "Заголовок новости" %><br>
        	<%= f.text_field :title, class: "form-control", autofocus: true, required: true  %>
        	<%= f.label "Добавить фото" %>
        	<%= f.file_field :image %>
        	<%= f.label "Текст новости" %>
        	<%= f.text_area :description, class: "form-control", autofocus: true, row: 10, coll: 10, required: true  %><br>
        	<%= f.submit "Создать новость" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/staticpages/contact_us.html.erb
<p>Мы открыты к сотруднечеству и предложениям.</p>
<p>Свяжитесь с нами если у вас возникли вопросы или 
вы хотите присоеденится к нам в качестве критика.</p>

<p><strong>email: info@critic.studio</strong></p>

<p>Если у вас остались вопросы по схеме работы с сервысом, мы будем рады 
ответить на ваши вопросы.</p>
<p></p>

<div class=cnt_us>
<p><strong>Отправить сообщение:</strong></p>
	<%= form_tag contact_us_path, method: :post, class: "form-inline" do %>
		<%= label_tag "Ваше имя" %><br>
		<%= text_field_tag :name, nil, class: "form-control", autofocus: true, size: 31, placeholder: "Петр Иванов", required: true %><br>
		<%= label_tag "Телефон" %><br>
		<%= telephone_field_tag :phone, nil, class: "form-control",size: 31, placeholder: "+ 7 (922) 555-1234", required: true %><br>
		<%= label_tag "Email" %><br>
		<%= email_field_tag :email, nil, class: "form-control", size: 31, placeholder: "ivanov@gmail.com", required: true %><br>
		<%= label_tag "Сообщение" %><br>
		<%= text_area_tag :message, nil, class: "form-control", cols:30, rows: 4, placeholder: "Как стать рецензентом?", required: true  %><br><br>
		<%= submit_tag "Отправить", name: nil, class: "btn btn-info", id: "cont_us_btn" %>
	<% end %>
</div>

app/views/staticpages/home.html.erb
<div class="text-left main">
	<h3><p class="lead"><h3>Вы:</h3></p> 
	<p><h4>Пишете стихи, прозу или сценарии?</h4></p>
	<h4>Хотите получить профиссиональный разбор своей работы, обективно оценить
	ее художествинные достоинства.</h4>
	<h4>Стремитесь развивать свои творчиские способности?</h4>
	<h4>Первый независимый сервис рецензии поможет Вам!</h4>
	<p><h4>Наши рецензенты - писатели, критики, редакторы ведущих литературных журналов и
	профессиональные сценаристы. Мы работаем исключительно с мастерами своего дела 
	и гарантируем юридическую защиту авторских прав.</h4></p>
	<p class="lead"><h3>Работать с нами просто, удобно, безопасно.</h3></p>
</div>

app/views/staticpages/how_it_works.html.erb
<div class="row">
	<div class="col-md-1 hitw_img">
		<i class="fa fa-users fa-5x" aria-hidden="true"></i>
	</div>
	<div class="col-md-2 hitw_title">
		1. Выберете рецензента
	</div>
	<div class="col-md-9 hitw_hint">
		<small>Во вкладке <%= link_to "рецензенты" %> вы можете ознакомится с полным списком
		наших критиков. Под именем критика указаны жанры, с которыми он работает.</small>
		<p><small>Прим.
		Будьте внимательны - если фото рецензента неактивно, это означает что он временно
		приостановил прием работ.</small></p>
		<p><small>Критики ранжированы по стоимости выполнения рецензии. В верхней части экрана -
		наиболее опытные и высокооплачиваемые мастера, ниже - начинающие, но не менее
		профессиональные коллеги с более бюджетным прейскурантом. Чтобы получить подробную
		информацию о критике, щелкните на иконку с его изображением. На странице
		рецензента можно ознакомится с его биографией и концепцией рецензирования, а
		затем отправить работу.</small></p>
		<p><small>Прим.
		Рекомендуем вам самостоятельно посчитать стоимость рецензии. Прайс-лист каждого
		рецензента расположен на его странице. Рассчитывая стоимость, учитывайте, что
		рукописи различных жанров могут оцениваться по-разному.</small></p>
	</div>
</div>
<div class="row">
	<div class="col-md-1 hitw_img2">
		<i class="fa fa-unlock fa-5x" aria-hidden="true"></i>
	</div>
	<div class="col-md-2 hitw_title2">
		2. Регистрация
	</div>
	<div class="col-md-9 hitw_hint2">
		<p><small>Итак, вы выбрали рецензента и готовы отправить рукопись.</small></p>
		<p><small>Заполните заявку(на странице рецензента или воспользовавшись клавишей "отправить
		работу" в верхней части экрана), ознакомьтесь с договором оферты и отправьте
		рукопись. ВНИМАНИЕ: мы принимаем файлы только в формате .doc.</small></p>
		<p><small>На почту, указанную в заявке, придет подтверждение регистрации на сайте и сообщение
		о получении заявки.</small></p>
	</div>
</div>
<div class="row">
	<div class="col-md-1 hitw_img3">
		<i class="fa fa-clock-o fa-5x" aria-hidden="true"></i>
	</div>
	<div class="col-md-2 hitw_title3">
		3. Рассмотрение заявки
	</div>
	<div class="col-md-9 hitw_hint2">
		<p><small>В течении трех дней со дня отправки работы мы ответим, принята ли она к 
		рецензированию. Рецензент имеет право отказаться от работы без объяснения причин.
		В случае если рецензент принял вашу заявку, мы вышлем вам уведомление и сформируем
		счет для оплаты.</small></p>
	</div>
</div>

<div class="row">
	<div class="col-md-1 hitw_img2">
		<i class="fa fa-credit-card fa-5x" aria-hidden="true"></i>
	</div>
	<div class="col-md-2 hitw_title4">
		4. Оплата
	</div>
	<div class="col-md-9 hitw_hint4">
		<p><small>Мы принимаем электронные платежи через Яндекс.деньги и переводы на расчетный счет.
		Оплата должна быть произведена в течении трех дней с момента получения счета.
		После подтверждения оплаты рецензент приступает к работе. Если оплата не поступает,
		мы освобождаем рецензента и высылаем Вам уведомление.</small></p>
	</div>
</div>

<div class="row">
	<div class="col-md-1 hitw_img2">
		<i class="fa fa-file-text-o fa-5x" aria-hidden="true"></i>
	</div>
	<div class="col-md-2 hitw_title5">
		5. Получение рецензии
	</div>
	<div class="col-md-9 hitw_hint5">
		<p><small>Рецензия будет готова через две недели после подтверждения заказа и его оплаты.
		Вы получаете рецензию напечатанную на фирменном бланке проекта "Экспертиза" в
		электронном виде. Если вы хотите получить рецензию с личной подписью рецензента,
		вы можете воспользоваться дополнительной услугой, обратившись к координатору в 
		ответном письме.</small></p>
	</div>
</div>

app/views/staticpages/information.html.erb
<div class="text-left info">
	<p>Проект "Экспертиза" - независимый сервис рецензирования, цель которого
  помочь авторам, заинтересованным в профессиональном росте. Наши друзья и
  партнеры - московская школа литературного творчества <strong>Creative Writing 
  School</strong>. Совместно с CWS мы работаем не только в сфере обучения и создания
  интеллектуального коммьюнити, но и активного продвижения наших авторов.</p>

  <p class="lead">Зачем это нужно?</p>
  <p>Воспользовавшись нашим сервисом вы получите:</p>
  <p>- профессиональный и беспристрастный анализ своего текста, который поможет
  обратить внимание на нюансы и "отшлифовать" текст;</p>
  <p>- четкую оценку: стоит ли публиковать работу или текст требует доработки;</p>
  <p>- вектор развития: каким конкретным изданиям стоит направить именно вашу
  рукопись для публикации;</p>
  <p>- автоматический допуск к совместному конкурсу проекта "Экспертиза" и "CWS"
  на публикацию в первой бесплатной городской литературной газете "GRAM". По
  итогам ежеквартального конкурса мы будем выбирать лучшие работы, прошедшие
  через наш сервис и публиковать их в нашей газете. Авторам опубликованных
  работ не только будет возвращена стоимость рецензии, но и предложен гонорар,
  пропорциональный объему работы.</p>      	 
</div>

app/views/staticpages/news.html.erb
<div class="media">
  <a class="media-left" href="#">
    <img class="thumbnail" src="cat.jpeg" >
  </a>
  <div class="media-body">
    <h4 class="media-heading">Название новости</h4>
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc facilisis magna vel mauris lobortis iaculis. Suspendisse venenatis mauris non rutrum bibendum. Proin luctus lorem ac mauris porttitor fringilla. Cras varius dapibus enim, eget sollicitudin est convallis a. Nunc pretium mollis molestie. Maecenas ac tortor id purus luctus feugiat. Donec consectetur dolor nec nisl hendrerit tincidunt.

Etiam venenatis varius nisi et ultrices. Ut commodo risus quis lectus sodales fermentum. Duis at felis aliquet, iaculis nunc ac, hendrerit dolor. Morbi vitae est quis nunc maximus laoreet. Cras faucibus in felis in interdum. Ut eget leo vel dolor pretium ultrices non quis felis. Aliquam bibendum erat vitae augue faucibus maximus.

Etiam ut libero sed mauris dapibus congue vel ac dui. Morbi commodo purus vitae metus sodales, a dapibus enim elementum. Curabitur a facilisis risus. Vestibulum nec elementum erat, in mattis ipsum. Donec at tristique magna. Morbi at enim risus. Phasellus id quam sit amet urna hendrerit mattis vel a purus. Phasellus magna justo, euismod sed odio eget, bibendum tincidunt lectus. Nulla facilisi.

Morbi risus diam, malesuada nec tempor pharetra, faucibus fringilla risus. Aliquam vestibulum bibendum quam. Aliquam quam est, sodales nec arcu nec, finibus pretium justo. In hac habitasse platea dictumst. Integer tincidunt lobortis orci sit amet elementum. Aenean interdum et purus et pretium. Nunc non eros euismod, luctus elit id, porta ipsum. Mauris efficitur lobortis posuere. Nunc porttitor lectus sed dictum molestie. Praesent lobortis, arcu id aliquet laoreet, tortor felis ultricies justo, dignissim semper velit lorem sed nisi. Mauris accumsan ex eu diam feugiat sagittis. Sed lacinia quam eu nulla pretium, at dapibus diam congue. Curabitur nec pretium libero, ut mattis nisl.

Maecenas ut tempor lorem. Aliquam erat volutpat. Mauris augue diam, elementum in pharetra a, imperdiet euismod ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec eget gravida sapien, sit amet dignissim lorem. Phasellus auctor, nunc at fringilla viverra, ex arcu finibus nibh, et condimentum nunc ligula quis nisi. Sed orci leo, eleifend at condimentum sed, porta sit amet libero. Ut euismod in nibh vel elementum. Nam aliquet ultrices dui feugiat vehicula. Phasellus massa nibh, efficitur ac quam sed, consequat consectetur dui. 
  </div>
</div>

app/views/users/_reviwer_profile.html.erb
<div class="row">
	<div class="col-md-2">
		<%= image_tag @user.avatar.url(:medium), class: "img-circle" %>
	</div>
	<div class="col-md-10 sh_pr">
		<h4 class="lead"><%= @user.name %></h4>
		<%= link_to "Редактировать профиль", edit_user_registration_path %>
		<button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">Добавить биографию</button>
		<h5>заявки() / в работе()</h5>
		<hr>
	</div>
</div>


<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
        	<%= render 'biographies/create' %>
      </div>
    </div>

  </div>
</div>

app/views/users/_user_profile.html.erb
<div class="row">
	<div class="col-md-2">
		<%= image_tag @user.avatar.url(:medium), class: "img-circle" %>
	</div>
	<div class="col-md-10 sh_pr">
		<h4 class="lead"><%= @user.name %></h4>
		<%= link_to "Редактировать профиль", edit_user_registration_path %><br>
		<h6>на рассмотрении() / завершенные()</h6>			
		<hr>
	</div>
</div>

app/views/users/index.html.erb
<% @reviwers.each do |r| %>
<div style="display:inline-block; width:49%">
		<%= image_tag r.avatar.url(:thumb), class: "img-circle", style:"float:left" %>

		<h4><%= link_to "#{r.name}", reviwer_show_path(r) %></h4>
		<% if r.biography %>
			<h6><%= r.biography.slogan %></h6>
		<% end %>
			<h6>Рейтинг: <%= r.rating %> (10)</h6>
		<h5><%= link_to "Отправить работу" %></h5> 
</div>

<% end %>

app/views/users/show.html.erb
<% if user_signed_in? && current_user.id == @user.id %>
		<% if current_user.role == "user" %>	
			<%= render 'users/user_profile' %>
		<% elsif current_user.role == "reviwer" %>
			<%= render 'users/reviwer_profile' %>
		<% end %>
<% end %>

app/views/work_genres/create.html.erb
<h1>WorkGenres#create</h1>
<p>Find me in app/views/work_genres/create.html.erb</p>

app/views/work_genres/destroy.html.erb
<h1>WorkGenres#destroy</h1>
<p>Find me in app/views/work_genres/destroy.html.erb</p>

app/views/work_genres/index.html.erb
<h1>WorkGenres#index</h1>
<p>Find me in app/views/work_genres/index.html.erb</p>